services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5433:5432
    env_file:
      - .env
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    networks:
      - roadilog-network

  node:
    container_name: node
    build: ./
    ports:
      - 5000:5000
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - roadilog-network

volumes:
  postgres-volume:

networks:
  roadilog-network:
    external: true
