on:
  push:
    branches:
      - main
name: Build and Deploy on AWS
jobs:
  build-and-deploy:
    runs-on: self-hosted
    timeout-minutes: 10
    steps:
      - name: Checkout back-end code
        uses: actions/checkout@v3
        with:
          repository: stonasss/RoadiLog-API # Replace with your back-end repository URL
          path: back-end
      - name: Checkout front-end code
        uses: actions/checkout@v3
        with:
          repository: stonasss/RoadiLog # Replace with your front-end repository URL
          path: front-end
      - name: Create back-end env file
        uses: SpicyPizza/create-envfile@v1.3.1
        with:
          envkey_PORT: ${{secrets.PORT}}
          envkey_DATABASE_URL: ${{secrets.DATABASE_URL}}
          envkey_POSTGRES_USERNAME: ${{secrets.POSTGRES_USERNAME}}
          envkey_POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          envkey_SECRET_KEY: ${{secrets.SECRET_KEY}}
          envkey_POSTGRES_DB: ${{secrets.POSTGRES_DB}}
          directory: .
          file_name: .env
          fail_on_empty: true
      - name: Create front-end env file
        uses: SpicyPizza/create-envfile@v1.3.1
        with:
          envkey_VITE_APP_BACKEND_URL: ${{secrets.VITE_APP_BACKEND_URL}}
          directory: front-end
          file_name: .env
          fail_on_empty: true
      - name: Build and deploy back-end
        run: |
          cd back-end
          docker-compose up --build -d
      - name: Build and deploy front-end
        run: |
          cd front-end
          docker-compose up --build -d